In [1]:
import numpy as np

# Modified 1D array
arr = np.array([10, 20, 30, 40, 50])
print("Initial array:")
print(arr)

# Modified column to append
col = np.arange(100, 105).reshape(-1, 1)
print("Column to append:")
print(col)

# Reshape the initial array to be a column vector
arr_reshaped = arr.reshape(-1, 1)

# Append the new column
result = np.append(arr_reshaped, col, axis=1)
print("After appending column-wise:")
print(result)


Initial array:
[10 20 30 40 50]
Column to append:
[[100]
 [101]
 [102]
 [103]
 [104]]
After appending column-wise:
[[ 10 100]
 [ 20 101]
 [ 30 102]
 [ 40 103]
 [ 50 104]]


In [2]:
import numpy as np

# Modified 2D array
arr = np.array([[10, 20, 30, 40, 50]])
print("Initial 2D array:")
print(arr)

# Modified row to append
row = np.array([60, 70, 80, 90, 100]).reshape(1, -1)
print("Row to append:")
print(row)

# Append the new row
result = np.append(arr, row, axis=0)
print("After appending row-wise:")
print(result)


Initial 2D array:
[[10 20 30 40 50]]
Row to append:
[[ 60  70  80  90 100]]
After appending row-wise:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
